name: Test GitHub Actions

on:
  push:
    branches:
      - main  # Se déclenche quand tu pousses du code sur la branche main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clone ton repo dans l’environnement GitHub Actions

      - name: Run a simple command
        run: echo "🎉 GitHub Actions fonctionne !"
